# Generated by Django 2.2.2 on 2019-06-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(null=True, verbose_name='写作时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='ttitle', max_length=16, verbose_name='标题'),
        ),
    ]
